//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Input/MainAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/MainAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MainAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MainAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""MainAction"",
    ""maps"": [
        {
            ""name"": ""KeyboardControl"",
            ""id"": ""20587219-0232-4330-8b67-8317765ee981"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""e3cd9535-3a97-41c8-8279-070cd87b60d8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""5bb0914d-f8ec-416f-b608-340d496c1f7f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""4e6da400-c994-41b8-b841-775a85c6ee07"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Skew"",
                    ""type"": ""Value"",
                    ""id"": ""5ade4ca7-6db2-490d-a811-14dd81cf4936"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Map"",
                    ""type"": ""Button"",
                    ""id"": ""d917b44a-efda-44f6-8bfb-1678457b0103"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MainInteract"",
                    ""type"": ""Button"",
                    ""id"": ""bab45d5e-a03f-4171-b547-b58a6469117f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""1ddce7b7-2e55-4c5f-bd95-4e4aa08ba73e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2556c0e7-5c63-41cd-a798-670611b3491a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7e8b253f-6626-4d31-a86e-cb1950496a57"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9ac3d1a9-1691-4b8d-8a40-8189ab4c47de"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b11cdd49-14e5-46e6-bb5f-b9ef09e74886"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""158ad21c-14fa-462c-82f2-c1fbd96033a4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""339542c8-af6a-49e0-850a-ab743dedba01"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""ae6cb25b-4f1d-4394-b3a8-ba59a7e780ed"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""60a69b53-eaa8-4bc4-a5a7-3daa1e915f8d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skew"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1fe68ae8-98ab-4d05-95be-e3c87e1ad386"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Skew"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b1feba86-134b-45ba-ab1c-6a108b545b1e"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Skew"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""ca0e6785-7b8d-4dba-b367-e96fc215d837"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""71763616-08a9-4d01-b844-783afcd75f66"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6973bb9b-b611-44e1-8b2c-3dc6933e7baa"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fdcd4410-8283-4881-bf76-db930b7f356b"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97e7530f-4488-4e9e-984e-de1d5051964a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MouseControl"",
            ""id"": ""fdaa4c54-5b65-4367-983d-77bdacfb2860"",
            ""actions"": [
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""b3cc98ab-a940-4f1b-b483-88987fc9775c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""f5f1e215-80da-42d3-96bf-8dfb885865c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightDouble"",
                    ""type"": ""Button"",
                    ""id"": ""236085ac-2e17-4103-9912-7e8084eb2af0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Middle"",
                    ""type"": ""Button"",
                    ""id"": ""bb8f42de-4de0-4b4e-9c27-11cf8a924dd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""cd4c4852-4e8a-40ae-a63f-75ce0ce8123a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""37d459b6-2550-48b8-88f8-5583a1a0cb02"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightHold"",
                    ""type"": ""Button"",
                    ""id"": ""d2d98a75-8d7b-4edc-8433-bf3fca153efe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleHold"",
                    ""type"": ""Button"",
                    ""id"": ""5b671bc0-8eb1-4af0-8669-52f3d920ea6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dc900831-520f-40fb-8677-c38a4151c3ca"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a42d5fc3-fd31-491f-9caa-ebdc7e79962f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f032eb3-7dc2-408a-bb4a-48c1488f449d"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Middle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""232b1acf-b2b4-40eb-9588-cacc9123a3ba"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d67d4071-2ce2-466b-a175-956d7192d420"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5f8f0d2-06e6-4f59-b11c-8593ef3988b6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDouble"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e011ca7-6126-4d26-87b2-e4dd1ff2edfb"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiddleHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97d8ed4f-fcff-4915-87e8-9b43c6c1ae80"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CreateMapControl"",
            ""id"": ""94936953-0923-4601-b187-4dbbfe43045c"",
            ""actions"": [
                {
                    ""name"": ""Brush"",
                    ""type"": ""Button"",
                    ""id"": ""f1639f24-403e-431f-b318-37ded2154bb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BorderBox"",
                    ""type"": ""Button"",
                    ""id"": ""ffe327e9-cab2-4515-b42c-bcb51b64df0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FilledBox"",
                    ""type"": ""Button"",
                    ""id"": ""d65eafd3-fe31-42e3-b39b-b589692756b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fill"",
                    ""type"": ""Button"",
                    ""id"": ""5133e4a9-d89f-42ce-9927-b4c2e7356b11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Erase"",
                    ""type"": ""Button"",
                    ""id"": ""2131cb7d-2c09-491b-bf7d-fb65a8ba149c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""be979577-c254-417c-8880-59208f1219c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RollBack"",
                    ""type"": ""Button"",
                    ""id"": ""37e244ba-8f1d-4bdb-a597-b3e589ba7998"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RollBackHold"",
                    ""type"": ""Button"",
                    ""id"": ""84a8f21c-ba74-40dc-8437-bc0256810096"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReRollBack"",
                    ""type"": ""Button"",
                    ""id"": ""dab0cda5-7540-4b39-bedd-27783f0267d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReRollBackHold"",
                    ""type"": ""Button"",
                    ""id"": ""9af2df4b-9cf6-42d9-8714-acb4433805fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadMap"",
                    ""type"": ""Button"",
                    ""id"": ""d9b2da97-d64f-4054-b99b-2201d18551f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""42cafd0e-74ed-4d15-8ef5-a1f6d238224d"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b2be750-2c90-4bfa-844a-b748f4b2292d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BorderBox"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6a901a6-e2a0-4a7f-b8f7-b154543324a0"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FilledBox"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d3a81b0-f9a8-439a-a853-521db6f8da7f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72dc48ab-b75a-4632-b6a6-e59a7163e4a5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Erase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d622b18f-1998-4341-8796-9b8269ec2377"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd61a201-9848-4796-bdd6-c2e8244051e7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1f82739-1a70-4abb-a8d5-a8c2d48b60c9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollBackHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9d424f4-c67f-499e-ad44-bb438e34d00e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReRollBackHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c64bf703-a735-47d0-971e-a39ac1a890dc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReRollBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ae8f19a-027c-46f8-ba7b-5145423602f9"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        }
    ]
}");
        // KeyboardControl
        m_KeyboardControl = asset.FindActionMap("KeyboardControl", throwIfNotFound: true);
        m_KeyboardControl_Move = m_KeyboardControl.FindAction("Move", throwIfNotFound: true);
        m_KeyboardControl_Rotation = m_KeyboardControl.FindAction("Rotation", throwIfNotFound: true);
        m_KeyboardControl_Zoom = m_KeyboardControl.FindAction("Zoom", throwIfNotFound: true);
        m_KeyboardControl_Skew = m_KeyboardControl.FindAction("Skew", throwIfNotFound: true);
        m_KeyboardControl_Map = m_KeyboardControl.FindAction("Map", throwIfNotFound: true);
        m_KeyboardControl_MainInteract = m_KeyboardControl.FindAction("MainInteract", throwIfNotFound: true);
        // MouseControl
        m_MouseControl = asset.FindActionMap("MouseControl", throwIfNotFound: true);
        m_MouseControl_Left = m_MouseControl.FindAction("Left", throwIfNotFound: true);
        m_MouseControl_Right = m_MouseControl.FindAction("Right", throwIfNotFound: true);
        m_MouseControl_RightDouble = m_MouseControl.FindAction("RightDouble", throwIfNotFound: true);
        m_MouseControl_Middle = m_MouseControl.FindAction("Middle", throwIfNotFound: true);
        m_MouseControl_Position = m_MouseControl.FindAction("Position", throwIfNotFound: true);
        m_MouseControl_Scroll = m_MouseControl.FindAction("Scroll", throwIfNotFound: true);
        m_MouseControl_RightHold = m_MouseControl.FindAction("RightHold", throwIfNotFound: true);
        m_MouseControl_MiddleHold = m_MouseControl.FindAction("MiddleHold", throwIfNotFound: true);
        // CreateMapControl
        m_CreateMapControl = asset.FindActionMap("CreateMapControl", throwIfNotFound: true);
        m_CreateMapControl_Brush = m_CreateMapControl.FindAction("Brush", throwIfNotFound: true);
        m_CreateMapControl_BorderBox = m_CreateMapControl.FindAction("BorderBox", throwIfNotFound: true);
        m_CreateMapControl_FilledBox = m_CreateMapControl.FindAction("FilledBox", throwIfNotFound: true);
        m_CreateMapControl_Fill = m_CreateMapControl.FindAction("Fill", throwIfNotFound: true);
        m_CreateMapControl_Erase = m_CreateMapControl.FindAction("Erase", throwIfNotFound: true);
        m_CreateMapControl_Save = m_CreateMapControl.FindAction("Save", throwIfNotFound: true);
        m_CreateMapControl_RollBack = m_CreateMapControl.FindAction("RollBack", throwIfNotFound: true);
        m_CreateMapControl_RollBackHold = m_CreateMapControl.FindAction("RollBackHold", throwIfNotFound: true);
        m_CreateMapControl_ReRollBack = m_CreateMapControl.FindAction("ReRollBack", throwIfNotFound: true);
        m_CreateMapControl_ReRollBackHold = m_CreateMapControl.FindAction("ReRollBackHold", throwIfNotFound: true);
        m_CreateMapControl_LoadMap = m_CreateMapControl.FindAction("LoadMap", throwIfNotFound: true);
    }

    ~@MainAction()
    {
        UnityEngine.Debug.Assert(!m_KeyboardControl.enabled, "This will cause a leak and performance issues, MainAction.KeyboardControl.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_MouseControl.enabled, "This will cause a leak and performance issues, MainAction.MouseControl.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CreateMapControl.enabled, "This will cause a leak and performance issues, MainAction.CreateMapControl.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KeyboardControl
    private readonly InputActionMap m_KeyboardControl;
    private List<IKeyboardControlActions> m_KeyboardControlActionsCallbackInterfaces = new List<IKeyboardControlActions>();
    private readonly InputAction m_KeyboardControl_Move;
    private readonly InputAction m_KeyboardControl_Rotation;
    private readonly InputAction m_KeyboardControl_Zoom;
    private readonly InputAction m_KeyboardControl_Skew;
    private readonly InputAction m_KeyboardControl_Map;
    private readonly InputAction m_KeyboardControl_MainInteract;
    /// <summary>
    /// Provides access to input actions defined in input action map "KeyboardControl".
    /// </summary>
    public struct KeyboardControlActions
    {
        private @MainAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public KeyboardControlActions(@MainAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_KeyboardControl_Move;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/Rotation".
        /// </summary>
        public InputAction @Rotation => m_Wrapper.m_KeyboardControl_Rotation;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/Zoom".
        /// </summary>
        public InputAction @Zoom => m_Wrapper.m_KeyboardControl_Zoom;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/Skew".
        /// </summary>
        public InputAction @Skew => m_Wrapper.m_KeyboardControl_Skew;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/Map".
        /// </summary>
        public InputAction @Map => m_Wrapper.m_KeyboardControl_Map;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/MainInteract".
        /// </summary>
        public InputAction @MainInteract => m_Wrapper.m_KeyboardControl_MainInteract;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_KeyboardControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="KeyboardControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(KeyboardControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="KeyboardControlActions" />
        public void AddCallbacks(IKeyboardControlActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @Skew.started += instance.OnSkew;
            @Skew.performed += instance.OnSkew;
            @Skew.canceled += instance.OnSkew;
            @Map.started += instance.OnMap;
            @Map.performed += instance.OnMap;
            @Map.canceled += instance.OnMap;
            @MainInteract.started += instance.OnMainInteract;
            @MainInteract.performed += instance.OnMainInteract;
            @MainInteract.canceled += instance.OnMainInteract;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="KeyboardControlActions" />
        private void UnregisterCallbacks(IKeyboardControlActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @Skew.started -= instance.OnSkew;
            @Skew.performed -= instance.OnSkew;
            @Skew.canceled -= instance.OnSkew;
            @Map.started -= instance.OnMap;
            @Map.performed -= instance.OnMap;
            @Map.canceled -= instance.OnMap;
            @MainInteract.started -= instance.OnMainInteract;
            @MainInteract.performed -= instance.OnMainInteract;
            @MainInteract.canceled -= instance.OnMainInteract;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="KeyboardControlActions.UnregisterCallbacks(IKeyboardControlActions)" />.
        /// </summary>
        /// <seealso cref="KeyboardControlActions.UnregisterCallbacks(IKeyboardControlActions)" />
        public void RemoveCallbacks(IKeyboardControlActions instance)
        {
            if (m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="KeyboardControlActions.AddCallbacks(IKeyboardControlActions)" />
        /// <seealso cref="KeyboardControlActions.RemoveCallbacks(IKeyboardControlActions)" />
        /// <seealso cref="KeyboardControlActions.UnregisterCallbacks(IKeyboardControlActions)" />
        public void SetCallbacks(IKeyboardControlActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="KeyboardControlActions" /> instance referencing this action map.
    /// </summary>
    public KeyboardControlActions @KeyboardControl => new KeyboardControlActions(this);

    // MouseControl
    private readonly InputActionMap m_MouseControl;
    private List<IMouseControlActions> m_MouseControlActionsCallbackInterfaces = new List<IMouseControlActions>();
    private readonly InputAction m_MouseControl_Left;
    private readonly InputAction m_MouseControl_Right;
    private readonly InputAction m_MouseControl_RightDouble;
    private readonly InputAction m_MouseControl_Middle;
    private readonly InputAction m_MouseControl_Position;
    private readonly InputAction m_MouseControl_Scroll;
    private readonly InputAction m_MouseControl_RightHold;
    private readonly InputAction m_MouseControl_MiddleHold;
    /// <summary>
    /// Provides access to input actions defined in input action map "MouseControl".
    /// </summary>
    public struct MouseControlActions
    {
        private @MainAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MouseControlActions(@MainAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MouseControl/Left".
        /// </summary>
        public InputAction @Left => m_Wrapper.m_MouseControl_Left;
        /// <summary>
        /// Provides access to the underlying input action "MouseControl/Right".
        /// </summary>
        public InputAction @Right => m_Wrapper.m_MouseControl_Right;
        /// <summary>
        /// Provides access to the underlying input action "MouseControl/RightDouble".
        /// </summary>
        public InputAction @RightDouble => m_Wrapper.m_MouseControl_RightDouble;
        /// <summary>
        /// Provides access to the underlying input action "MouseControl/Middle".
        /// </summary>
        public InputAction @Middle => m_Wrapper.m_MouseControl_Middle;
        /// <summary>
        /// Provides access to the underlying input action "MouseControl/Position".
        /// </summary>
        public InputAction @Position => m_Wrapper.m_MouseControl_Position;
        /// <summary>
        /// Provides access to the underlying input action "MouseControl/Scroll".
        /// </summary>
        public InputAction @Scroll => m_Wrapper.m_MouseControl_Scroll;
        /// <summary>
        /// Provides access to the underlying input action "MouseControl/RightHold".
        /// </summary>
        public InputAction @RightHold => m_Wrapper.m_MouseControl_RightHold;
        /// <summary>
        /// Provides access to the underlying input action "MouseControl/MiddleHold".
        /// </summary>
        public InputAction @MiddleHold => m_Wrapper.m_MouseControl_MiddleHold;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MouseControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MouseControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MouseControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MouseControlActions" />
        public void AddCallbacks(IMouseControlActions instance)
        {
            if (instance == null || m_Wrapper.m_MouseControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MouseControlActionsCallbackInterfaces.Add(instance);
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @RightDouble.started += instance.OnRightDouble;
            @RightDouble.performed += instance.OnRightDouble;
            @RightDouble.canceled += instance.OnRightDouble;
            @Middle.started += instance.OnMiddle;
            @Middle.performed += instance.OnMiddle;
            @Middle.canceled += instance.OnMiddle;
            @Position.started += instance.OnPosition;
            @Position.performed += instance.OnPosition;
            @Position.canceled += instance.OnPosition;
            @Scroll.started += instance.OnScroll;
            @Scroll.performed += instance.OnScroll;
            @Scroll.canceled += instance.OnScroll;
            @RightHold.started += instance.OnRightHold;
            @RightHold.performed += instance.OnRightHold;
            @RightHold.canceled += instance.OnRightHold;
            @MiddleHold.started += instance.OnMiddleHold;
            @MiddleHold.performed += instance.OnMiddleHold;
            @MiddleHold.canceled += instance.OnMiddleHold;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MouseControlActions" />
        private void UnregisterCallbacks(IMouseControlActions instance)
        {
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @RightDouble.started -= instance.OnRightDouble;
            @RightDouble.performed -= instance.OnRightDouble;
            @RightDouble.canceled -= instance.OnRightDouble;
            @Middle.started -= instance.OnMiddle;
            @Middle.performed -= instance.OnMiddle;
            @Middle.canceled -= instance.OnMiddle;
            @Position.started -= instance.OnPosition;
            @Position.performed -= instance.OnPosition;
            @Position.canceled -= instance.OnPosition;
            @Scroll.started -= instance.OnScroll;
            @Scroll.performed -= instance.OnScroll;
            @Scroll.canceled -= instance.OnScroll;
            @RightHold.started -= instance.OnRightHold;
            @RightHold.performed -= instance.OnRightHold;
            @RightHold.canceled -= instance.OnRightHold;
            @MiddleHold.started -= instance.OnMiddleHold;
            @MiddleHold.performed -= instance.OnMiddleHold;
            @MiddleHold.canceled -= instance.OnMiddleHold;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MouseControlActions.UnregisterCallbacks(IMouseControlActions)" />.
        /// </summary>
        /// <seealso cref="MouseControlActions.UnregisterCallbacks(IMouseControlActions)" />
        public void RemoveCallbacks(IMouseControlActions instance)
        {
            if (m_Wrapper.m_MouseControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MouseControlActions.AddCallbacks(IMouseControlActions)" />
        /// <seealso cref="MouseControlActions.RemoveCallbacks(IMouseControlActions)" />
        /// <seealso cref="MouseControlActions.UnregisterCallbacks(IMouseControlActions)" />
        public void SetCallbacks(IMouseControlActions instance)
        {
            foreach (var item in m_Wrapper.m_MouseControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MouseControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MouseControlActions" /> instance referencing this action map.
    /// </summary>
    public MouseControlActions @MouseControl => new MouseControlActions(this);

    // CreateMapControl
    private readonly InputActionMap m_CreateMapControl;
    private List<ICreateMapControlActions> m_CreateMapControlActionsCallbackInterfaces = new List<ICreateMapControlActions>();
    private readonly InputAction m_CreateMapControl_Brush;
    private readonly InputAction m_CreateMapControl_BorderBox;
    private readonly InputAction m_CreateMapControl_FilledBox;
    private readonly InputAction m_CreateMapControl_Fill;
    private readonly InputAction m_CreateMapControl_Erase;
    private readonly InputAction m_CreateMapControl_Save;
    private readonly InputAction m_CreateMapControl_RollBack;
    private readonly InputAction m_CreateMapControl_RollBackHold;
    private readonly InputAction m_CreateMapControl_ReRollBack;
    private readonly InputAction m_CreateMapControl_ReRollBackHold;
    private readonly InputAction m_CreateMapControl_LoadMap;
    /// <summary>
    /// Provides access to input actions defined in input action map "CreateMapControl".
    /// </summary>
    public struct CreateMapControlActions
    {
        private @MainAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CreateMapControlActions(@MainAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/Brush".
        /// </summary>
        public InputAction @Brush => m_Wrapper.m_CreateMapControl_Brush;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/BorderBox".
        /// </summary>
        public InputAction @BorderBox => m_Wrapper.m_CreateMapControl_BorderBox;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/FilledBox".
        /// </summary>
        public InputAction @FilledBox => m_Wrapper.m_CreateMapControl_FilledBox;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/Fill".
        /// </summary>
        public InputAction @Fill => m_Wrapper.m_CreateMapControl_Fill;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/Erase".
        /// </summary>
        public InputAction @Erase => m_Wrapper.m_CreateMapControl_Erase;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/Save".
        /// </summary>
        public InputAction @Save => m_Wrapper.m_CreateMapControl_Save;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/RollBack".
        /// </summary>
        public InputAction @RollBack => m_Wrapper.m_CreateMapControl_RollBack;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/RollBackHold".
        /// </summary>
        public InputAction @RollBackHold => m_Wrapper.m_CreateMapControl_RollBackHold;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/ReRollBack".
        /// </summary>
        public InputAction @ReRollBack => m_Wrapper.m_CreateMapControl_ReRollBack;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/ReRollBackHold".
        /// </summary>
        public InputAction @ReRollBackHold => m_Wrapper.m_CreateMapControl_ReRollBackHold;
        /// <summary>
        /// Provides access to the underlying input action "CreateMapControl/LoadMap".
        /// </summary>
        public InputAction @LoadMap => m_Wrapper.m_CreateMapControl_LoadMap;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CreateMapControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CreateMapControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CreateMapControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CreateMapControlActions" />
        public void AddCallbacks(ICreateMapControlActions instance)
        {
            if (instance == null || m_Wrapper.m_CreateMapControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CreateMapControlActionsCallbackInterfaces.Add(instance);
            @Brush.started += instance.OnBrush;
            @Brush.performed += instance.OnBrush;
            @Brush.canceled += instance.OnBrush;
            @BorderBox.started += instance.OnBorderBox;
            @BorderBox.performed += instance.OnBorderBox;
            @BorderBox.canceled += instance.OnBorderBox;
            @FilledBox.started += instance.OnFilledBox;
            @FilledBox.performed += instance.OnFilledBox;
            @FilledBox.canceled += instance.OnFilledBox;
            @Fill.started += instance.OnFill;
            @Fill.performed += instance.OnFill;
            @Fill.canceled += instance.OnFill;
            @Erase.started += instance.OnErase;
            @Erase.performed += instance.OnErase;
            @Erase.canceled += instance.OnErase;
            @Save.started += instance.OnSave;
            @Save.performed += instance.OnSave;
            @Save.canceled += instance.OnSave;
            @RollBack.started += instance.OnRollBack;
            @RollBack.performed += instance.OnRollBack;
            @RollBack.canceled += instance.OnRollBack;
            @RollBackHold.started += instance.OnRollBackHold;
            @RollBackHold.performed += instance.OnRollBackHold;
            @RollBackHold.canceled += instance.OnRollBackHold;
            @ReRollBack.started += instance.OnReRollBack;
            @ReRollBack.performed += instance.OnReRollBack;
            @ReRollBack.canceled += instance.OnReRollBack;
            @ReRollBackHold.started += instance.OnReRollBackHold;
            @ReRollBackHold.performed += instance.OnReRollBackHold;
            @ReRollBackHold.canceled += instance.OnReRollBackHold;
            @LoadMap.started += instance.OnLoadMap;
            @LoadMap.performed += instance.OnLoadMap;
            @LoadMap.canceled += instance.OnLoadMap;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CreateMapControlActions" />
        private void UnregisterCallbacks(ICreateMapControlActions instance)
        {
            @Brush.started -= instance.OnBrush;
            @Brush.performed -= instance.OnBrush;
            @Brush.canceled -= instance.OnBrush;
            @BorderBox.started -= instance.OnBorderBox;
            @BorderBox.performed -= instance.OnBorderBox;
            @BorderBox.canceled -= instance.OnBorderBox;
            @FilledBox.started -= instance.OnFilledBox;
            @FilledBox.performed -= instance.OnFilledBox;
            @FilledBox.canceled -= instance.OnFilledBox;
            @Fill.started -= instance.OnFill;
            @Fill.performed -= instance.OnFill;
            @Fill.canceled -= instance.OnFill;
            @Erase.started -= instance.OnErase;
            @Erase.performed -= instance.OnErase;
            @Erase.canceled -= instance.OnErase;
            @Save.started -= instance.OnSave;
            @Save.performed -= instance.OnSave;
            @Save.canceled -= instance.OnSave;
            @RollBack.started -= instance.OnRollBack;
            @RollBack.performed -= instance.OnRollBack;
            @RollBack.canceled -= instance.OnRollBack;
            @RollBackHold.started -= instance.OnRollBackHold;
            @RollBackHold.performed -= instance.OnRollBackHold;
            @RollBackHold.canceled -= instance.OnRollBackHold;
            @ReRollBack.started -= instance.OnReRollBack;
            @ReRollBack.performed -= instance.OnReRollBack;
            @ReRollBack.canceled -= instance.OnReRollBack;
            @ReRollBackHold.started -= instance.OnReRollBackHold;
            @ReRollBackHold.performed -= instance.OnReRollBackHold;
            @ReRollBackHold.canceled -= instance.OnReRollBackHold;
            @LoadMap.started -= instance.OnLoadMap;
            @LoadMap.performed -= instance.OnLoadMap;
            @LoadMap.canceled -= instance.OnLoadMap;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CreateMapControlActions.UnregisterCallbacks(ICreateMapControlActions)" />.
        /// </summary>
        /// <seealso cref="CreateMapControlActions.UnregisterCallbacks(ICreateMapControlActions)" />
        public void RemoveCallbacks(ICreateMapControlActions instance)
        {
            if (m_Wrapper.m_CreateMapControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CreateMapControlActions.AddCallbacks(ICreateMapControlActions)" />
        /// <seealso cref="CreateMapControlActions.RemoveCallbacks(ICreateMapControlActions)" />
        /// <seealso cref="CreateMapControlActions.UnregisterCallbacks(ICreateMapControlActions)" />
        public void SetCallbacks(ICreateMapControlActions instance)
        {
            foreach (var item in m_Wrapper.m_CreateMapControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CreateMapControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CreateMapControlActions" /> instance referencing this action map.
    /// </summary>
    public CreateMapControlActions @CreateMapControl => new CreateMapControlActions(this);
    private int m_KeyboardSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "KeyboardControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="KeyboardControlActions.AddCallbacks(IKeyboardControlActions)" />
    /// <seealso cref="KeyboardControlActions.RemoveCallbacks(IKeyboardControlActions)" />
    public interface IKeyboardControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Zoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnZoom(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Skew" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSkew(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Map" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMap(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MainInteract" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMainInteract(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MouseControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MouseControlActions.AddCallbacks(IMouseControlActions)" />
    /// <seealso cref="MouseControlActions.RemoveCallbacks(IMouseControlActions)" />
    public interface IMouseControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightDouble" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightDouble(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Middle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMiddle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Position" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Scroll" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScroll(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightHold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightHold(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MiddleHold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMiddleHold(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CreateMapControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CreateMapControlActions.AddCallbacks(ICreateMapControlActions)" />
    /// <seealso cref="CreateMapControlActions.RemoveCallbacks(ICreateMapControlActions)" />
    public interface ICreateMapControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "Brush" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBrush(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BorderBox" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBorderBox(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FilledBox" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFilledBox(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Fill" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFill(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Erase" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnErase(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Save" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSave(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RollBack" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRollBack(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RollBackHold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRollBackHold(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ReRollBack" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReRollBack(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ReRollBackHold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReRollBackHold(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LoadMap" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLoadMap(InputAction.CallbackContext context);
    }
}
